import './core.js'

import './ui/avatar.js'
import './ui/banner.js'
import './ui/dropdown.js'
import './ui/dropdown_form.js'
import './ui/form.js'
import './ui/frame.js'
import './ui/indicator_text_input.js'
import './ui/infinite_scroller.js'
import './ui/local_number.js'
import './ui/local_time.js'
import './ui/modal.js'
import './ui/modal_form.js'
import './ui/nav.js'
import './ui/on_key.js'
import './ui/popover.js'
import './ui/popover_form.js'
import './ui/sortable.js'
import './ui/spinner.js'
import './ui/toast.js'
import './ui/tooltip.js'
import './ui/xhr.js'

Romo.setup()
